const DOMAIN_NAME = process.env.DOMAIN_NAME;

const WEBSOCKET_CONNECTIONS_TABLE = `websocket-connections`;
const WEBSOCKET_CONNECTIONS_INDEX_CONNECTION = `websocket-connections-index-connection`;

export {
  DOMAIN_NAME,
  WEBSOCKET_CONNECTIONS_TABLE,
  WEBSOCKET_CONNECTIONS_INDEX_CONNECTION,
};
