
---
AWSTemplateFormatVersion: '2010-09-09'
Description: Template for creating Cloudfront distribution from S3 with origin access identity and DNS records


Resources:
  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        HttpVersion: 'http2'
        Origins:
          - Id: !Join
                - ""
                - - "id-"
                  - Fn::ImportValue: "clap-app-angular-bucket-domain-name"
            DomainName: !Join
              - ''
              - - Fn::ImportValue: 'clap-app-angular-bucket-name'
                - !Sub '.s3-${AWS::Region}.amazonaws.com'
            S3OriginConfig:
              OriginAccessIdentity: !Join
                - ""
                - - "origin-access-identity/cloudfront/"
                  - Fn::ImportValue: "clap-app-s3-bucket-angular-cloudfront-oai"
        Enabled: 'true'
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        Aliases:
          - clap-app.net
        DefaultCacheBehavior:
          CachedMethods:
            - GET
            - HEAD
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - PATCH
            - POST
            - DELETE
          Compress: true
          DefaultTTL: 86400
          MaxTTL: 604800
          # CloudFront to route requests to when they use the default cache behavior.
          TargetOriginId: !Join
                - ""
                - - "id-"
                  - Fn::ImportValue: "clap-app-angular-bucket-domain-name"

          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_100

        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:177244120069:certificate/359c2568-8b53-434d-b39b-8a6e2b661d1d
          MinimumProtocolVersion: TLSv1.2_2018
          SslSupportMethod: sni-only

  DnsRecord:
    Type: AWS::Route53::RecordSet
    DependsOn: CloudfrontDistribution
    Properties:
      AliasTarget:
        DNSName: !GetAtt CloudfrontDistribution.DomainName
        # Constant value for CloudFront: Z2FDTNDATAQYW2
        HostedZoneId: 'Z2FDTNDATAQYW2'
      # route53 hosted zone id 
      HostedZoneId: Z05137671NYCOAKLDU04C
      Name: clap-app.net
      Type: A







