
---
AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB table for clap-app posts-likes

Resources:
  ClapAppPostsLikesTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
        - AttributeName: 'postId'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
      GlobalSecondaryIndexes:
        - IndexName: "postId-gsi"
          KeySchema:
            - AttributeName: "postId"
              KeyType: "HASH"
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      TableName: 'clap-app-posts-likes'
      StreamSpecification:
        StreamViewType: 'NEW_AND_OLD_IMAGES'
      Tags:
        - Key: Name
          Value: 'clap-app-posts-likes-table'
        - Key: Application
          Value: 'clap-app'

  ClapAppPostsLikesTableStreamArn:
    Description: clap-app posts-likes table stream ARN
    Value: !GetAtt ClapAppPostsLikesTable.StreamArn
    Export:
      Name: clap-app-posts-likes-table-stream-arn

Outputs:
  ClapAppPostsLikesTableArn:
    Description: clap-app posts-likes Table ARN
    Value: !GetAtt ClapAppPostsLikesTable.Arn
    Export:
      Name: clap-app-posts-likes-table-arn

