
---
AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB table for clap-app posts-medias

Resources:
  ClapAppPostsMediasTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
        - AttributeName: 'postId'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
      GlobalSecondaryIndexes:
        - IndexName: "postId-gsi"
          KeySchema:
            - AttributeName: "postId"
              KeyType: "HASH"
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      TableName: 'clap-app-posts-medias'
      StreamSpecification:
        StreamViewType: 'NEW_AND_OLD_IMAGES'
      Tags:
        - Key: Name
          Value: 'clap-app-posts-medias-table'
        - Key: Application
          Value: 'clap-app'

Outputs:
  ClapAppPostsMediasTableArn:
    Description: clap-app posts-medias Table ARN
    Value: !GetAtt ClapAppPostsMediasTable.Arn
    Export:
      Name: clap-app-posts-medias-table-arn

  ClapAppPostsMediasTableStreamArn:
    Description: clap-app posts-medias table stream ARN
    Value: !GetAtt ClapAppPostsMediasTable.StreamArn
    Export:
      Name: clap-app-posts-medias-table-stream-arn

