
---
AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB single table design

# komposiitti avain == PK & SK

Resources:
  ClapAppUsersTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: 'PK'
          AttributeType: 'S'
        - AttributeName: 'SK'
          AttributeType: 'S'
        - AttributeName: 'GS1PK'
          AttributeType: 'S'
        - AttributeName: 'GS1SK'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'PK'
          KeyType: 'HASH'
        - AttributeName: 'SK'
          KeyType: 'RANGE'
      GlobalSecondaryIndexes:
        - IndexName: "gs1"
          KeySchema:
            - AttributeName: "GS1PK"
              KeyType: "HASH"
            - AttributeName: "GS1SK"
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      TableName: 'single-table-design'
