
Description: S3 Bucket for reactive cognito lambda

Resources:
  ClapAppReactiveCognitoLambda:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: clap-app-reactive-cognito-lamda
      PublicAccessBlockConfiguration:
        BlockPublicAcls : true
        BlockPublicPolicy : true
        IgnorePublicAcls : true
        RestrictPublicBuckets : true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            MaxAge: "300"
            AllowedMethods:
              - GET
              - HEAD
              - POST
              - PUT
              - DELETE
            AllowedOrigins:
              - "*"
      Tags:
        - Key: name
          Value: S3 Bucket for clap-app reactive cognito lambda


Outputs:
  ClapAppReactiveCognitoLambdaDomainName:
    Description: S3 Bucket for clap-app reactive cognito lambda Domain Name
    Value: !GetAtt ClapAppReactiveCognitoLambda.DomainName
    Export:
      Name: clap-app-reactive-cognito-lambda-domain-name

