
Description: S3 Bucket for clap-app medias. Used with cloudfront distribution

Resources:
  ClapAppS3BucketMedias:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: clap-app-medias
      PublicAccessBlockConfiguration:
        BlockPublicAcls : true
        BlockPublicPolicy : true
        IgnorePublicAcls : true
        RestrictPublicBuckets : true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            ExposedHeaders:
              # encrypt an object at the time of upload
              - x-amz-server-side-encryption
              - x-amz-request-id
              - x-amz-id-2
              - ETag
            MaxAge: "300"
            AllowedMethods:
              - GET
              - HEAD
              - POST
              - PUT
              - DELETE
            AllowedOrigins:
              - "*"
      Tags:
        - Key: name
          Value: S3 Bucket for clap-app medias.

  CloudFrontOAIs3BucketMedias:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Origin Access Identity for distribution of s3 bucket for clap-app medias

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: ClapAppS3BucketMedias
    Properties:
      Bucket: !Ref ClapAppS3BucketMedias
      PolicyDocument:
        Statement:
            Effect: Allow
            Action:
              - 's3:GetObject'
            Resource:
                - !Sub "arn:aws:s3:::${ClapAppS3BucketMedias}/*"
            Principal:
              CanonicalUser: !GetAtt CloudFrontOAIs3BucketMedias.S3CanonicalUserId

Outputs:
  ClapAppS3BucketMediasDomainName:
    Description: clap-app medias s3 Bucket Domain Name
    Value: !GetAtt ClapAppS3BucketMedias.DomainName
    Export:
      Name: clap-app-medias-s3-bucket-domain-name

  # for cleanup lambda access
  ClapAppS3BucketMediasS3BucketARN:
    Description: clap-app-rofile medias S3 bucket ARN
    Value: !GetAtt ClapAppS3BucketMedias.Arn
    Export:
      Name: clap-app-medias-s3-bucket-arn

  CloudFrontOAIs3BucketMedias:
    Description: CloudFrontOAIs3BucketMedias
    Value: !Ref CloudFrontOAIs3BucketMedias
    Export:
      Name: clap-app-medias-s3-bucket-cloudfront-oai



