---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Reactive cleanups powered by Lambda functions

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  AllowLambdaDynamoDB:
    Type: AWS::IAM::Policy
    DependsOn:
      - LambdaExecutionRole
    Properties:
      PolicyName: 'AllowLambdaDynamoDB'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:*
            Resource:
              - '*'
      Roles:
        - !Ref LambdaExecutionRole

  AllowDynamoDBStreamSource:
    Type: AWS::IAM::Policy
    DependsOn:
      - LambdaExecutionRole
    Properties:
      PolicyName: 'AllowDynamoDBStreamSource'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:DescribeStream
              - dynamodb:ListStreams
            Resource:
              - Fn::ImportValue: clap-app-profile-images-table-stream-arn
      Roles:
        - !Ref LambdaExecutionRole

  AllowLambdaProfileImageBucket:
    Type: AWS::IAM::Policy
    DependsOn:
      - LambdaExecutionRole
    Properties:
      PolicyName: 'AllowLambdaProfileImageBucket'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:ListBucket
            Resource:
              - Fn::ImportValue: clap-app-profile-images-s3-bucket-arn
          - Effect: Allow
            Action:
              - s3:DeleteObject
              - s3:DeleteObjectVersion
            Resource:
              - !Join
                - ''
                - - Fn::ImportValue: clap-app-profile-images-s3-bucket-arn
                  - /*
      Roles:
        - !Ref LambdaExecutionRole

  ProfileImageDeletedLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../build
      Handler: profile-image-deleted-lambda.handler
      MemorySize: 128
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: nodejs14.x
      Timeout: 30

  ProfileImageDeletedStreamEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    DependsOn:
      - AllowDynamoDBStreamSource
    Properties:
      EventSourceArn:
        Fn::ImportValue: clap-app-profile-images-table-stream-arn
      FunctionName: !GetAtt ProfileImageDeletedLambda.Arn
      StartingPosition: 'TRIM_HORIZON'


